# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Let's Dig IT
tagline:             'feat. Junghyun Park'
#description:         ' <a href="http://jekyllrb.com" target="_blank"> Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Junghyun Park
  url:               https://twitter.com/mdo
  email:             parkjh688@gmail.com

# Custom vars
version:             1.0.0

# Gems
plugins: [jekyll-paginate]
